# Numpy
- based on https://github.com/mephistopheies/mlworkshop39_042017/blob/master/0_python_intro/%D0%A3%D0%BF%D1%80%D0%B0%D0%B6%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F.ipynb

<img src="trainings1.jpg" />

## Task 0
- import numpy

In [1]:
import numpy as np

## Task 1
- print version of numpy

In [3]:
print(np.version.version)

1.17.0


## Task 2
- create 1d vector of zeros of size 10

In [20]:
vecA = np.zeros((10))
print(vecA)
print(vecA.shape) #To verify that the vector is 1d or not

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(10,)


## Task 3
- create 1d vector filled with ones of size 10

In [6]:
vecB = np.ones((10))
print(vecB)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## Task 4
- create 1d vector filled with ones of size 10,

In [8]:
vecC = np.ones((10,10))
print(vecC)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## Task 5
- crete 1d vector filled with numbers from 10 to 49

In [24]:
arr = list(range(10,50))
print(arr)
vecE = np.array(arr);
print(vecE)
vecF = np.arange(10,50)
print(vecF)
print(vecF.shape) #To verify that the vector is 1d or not

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
(40,)


## Task 6
- create any 1d vector, then reverce it, such that last element will be on the first position

In [28]:
vecG = np.arange((10));
print(vecG)
vecH = np.flip(vecG)
print(vecH)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


## Task 7
- create 2d 3x3 array / matrix, filled with numbers from 0 to 8

In [30]:
vecI = np.arange(0,9).reshape(3,3)
print(vecI)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Task 8
- create 3x3 matrix filled with ones

In [36]:
vecJ = np.ones(9).reshape(3,3)
print(vecJ)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Task 9
- create 3x3 matrix filled with random numbers

In [47]:
vecK = np.random.rand(3,3)
print(vecK)

[[0.38670197 0.89964218 0.86187496]
 [0.19754391 0.63392395 0.76126707]
 [0.51780454 0.40347893 0.79022306]]


## Task 10
- create 3x3x3 array filled with random numbers

In [87]:
vec10 = np.random.randint(1,3000,(3,3,3))
print(vec10)
vec101 = np.random.rand(3,3,3)
print(vec101)

[[[2184   31  313]
  [  81 2600 2296]
  [  43 2195 1085]]

 [[1872 1366 1952]
  [1259 1624 1511]
  [ 942 1216  171]]

 [[2680  745 2977]
  [1779 2034 1268]
  [1077  703  259]]]
[[[0.92342837 0.32588111 0.8925312 ]
  [0.88426415 0.32797804 0.14428695]
  [0.12647944 0.36793295 0.6207224 ]]

 [[0.32225658 0.47244823 0.02405366]
  [0.43931294 0.96326194 0.85220097]
  [0.26022867 0.52546087 0.01358913]]

 [[0.64311907 0.85346359 0.90213847]
  [0.40618979 0.27327512 0.51624344]
  [0.34305461 0.29270707 0.82495737]]]


## Task 11
- create 10x10 matrix filled with random numbers and find minimal and maximal elements

In [86]:
mat11 = np.random.randint(1,1000,(10,10))
min11 = np.amin(mat11)
max11 = np.amax(mat11)
print(mat11)
print(min11)
print(max11)


[[726 362 440 760  29 770 670 718 455 511]
 [985 500 722 156 875 833 534  76 340 662]
 [517 185 177  47 212 420 284 905 979 861]
 [522 243 304 951 905 651 509 825 911 513]
 [650 392 468 267 261 206 445 791 434 770]
 [944 763 445 666 160 474 132 573 383 963]
 [885 427 380 937 518 887 463 633 382 457]
 [697 247 171 405 566 959 759 812 865 260]
 [321 958 344 952 345 122 276 199 822 962]
 [883 623 526 695 609 295 867 357 986 156]]
29
986


## Task 12
- create a random 1d vector of size 30 and find average of them

In [93]:
vec12 = np.random.randint(1,3000,(30)) #Random array of 30 index values 
avg12 = np.average(vec12)
print(vec12)
print(avg12)

[ 730 1500  591  705 2821 2949  403 1165 1329 1125 2310 2953  569 2768
 2482 1246 2650 1712 1404 1861 1707 2504 2656 2713 1949  922 1830  434
 1286 1153]
1680.9


## Task 13
- create 5x5 matrix, which has ones on a "frame" and zeros inside

In [202]:
mat13 = np.zeros((5,5),float)

for ind1,i in enumerate(mat13):
    for ind2, j in enumerate(i):
        if(ind1 == 0):
            mat13[ind1][ind2] = 1
        elif(ind1 == 4):
            mat13[ind1][ind2] = 1
        elif(ind2 == 0) or (ind2 ==4):
            mat13[ind1][ind2] = 1

print(mat13)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Task 14
- create 8x8 matrix
- fill it with ones and zeros in a "chess" order
- **don't use** `tile` funtion

In [147]:
mat14 = np.ones((8,8))

for ind1,i in enumerate(mat14):
    for ind2, j in enumerate(i):
        if(ind1 % 2  == 0):
            if(ind2 % 2 == 0):
                mat14[ind1][ind2] = 0
            else:
                mat14[ind1][ind2] = 1
        else:
            if(ind2 % 2 != 0):
                 mat14[ind1][ind2] = 0

print(mat14)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


## Task 15
- create 8x8 matrix
- fill it with ones and zeros in a "chess" order
- **use** `tile` funtion

In [203]:
mat15 = np.empty((8,8))
oneZ = np.array([1,0])
zOne = np.array([0,1])

for i in range(8):
    if(i == 0) or (i %2 == 0):
        mat15[i] = np.tile(oneZ,4)
    else:
        mat15[i] = np.tile(zOne,4)

print(mat15)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


## Task 16
- create two random matrices 5x3 and 3x2
- multiply them

In [159]:
mat16a = np.random.randint(1, 10, size = (5,3))
mat16b = np.random.randint(1, 10, size = (3,2))

x = np.arange(15).reshape(5,3)
y = np.arange(6).reshape(3,2)

mat16 = np.multiply(x,y)
print(mat16)

ValueError: operands could not be broadcast together with shapes (5,3) (3,2) 

## Task 17
- create array of size 100 filled with random numbers from 0 to 10
- chenge sign of all numbers which are in a range between 3 and 8

In [188]:
mat17 = np.random.randint(0,10,(100,))

for index,val in enumerate(mat17):
    if((val >= 3) and (val <= 8)):
        mat17[index] = np.negative(mat17[index])
        
print(mat17)

[-4 -6  9  0 -6 -5 -4  9 -6 -5 -4  0 -8  0 -5 -8 -7 -5 -3 -5 -6 -3  0 -7
 -6 -3 -4  2  2  2 -5 -8 -3 -3 -6 -4  2 -4  2  9 -7  9 -7 -4  1  9 -8  2
 -6  0  2 -8 -7 -5 -3  9  1 -4  0  9  2  1  2 -4 -7 -8  1  9 -7 -3 -7 -5
 -7  1 -8  1 -8 -7 -4  9  0  0  2 -7  0 -4 -3 -6 -6  9  2  1  9 -7 -3  2
 -8 -4 -5  2]


## Task 18
- create a matrix 5x5 such that each row would be a 1d array filled with numbers from 0 to 4

In [207]:
arr = np.arange(5)

for i in range(5):
    mat18[i] = arr;

print(mat18)
    

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## Task 19
- create 1d vector of size 100 filled with random values from range 0-1, excluding boundary values (no exact 0/1)

In [215]:
vec19 = np.random.rand((100))
print(vec19)

[0.04652301 0.7706494  0.70641019 0.38780664 0.87813741 0.60747564
 0.54187898 0.34595877 0.22007713 0.47609011 0.27521294 0.51224581
 0.76235038 0.68777275 0.37244453 0.4185565  0.2012166  0.81769688
 0.2031388  0.53727258 0.10961439 0.29990422 0.72496991 0.48418031
 0.15948978 0.43204388 0.79645915 0.32442946 0.80620287 0.1718355
 0.62726692 0.40025758 0.52621152 0.46026162 0.87718235 0.32482283
 0.08751672 0.95420997 0.21637956 0.96342623 0.70387923 0.55215416
 0.00526572 0.66427477 0.73706649 0.85705039 0.2279074  0.97622564
 0.59064303 0.94705551 0.23920592 0.70685305 0.38289077 0.64620745
 0.20278346 0.3521781  0.617146   0.67101374 0.8741148  0.46399183
 0.23304344 0.38706621 0.01271983 0.81267361 0.40165343 0.38083964
 0.92099375 0.99857012 0.04498752 0.44814118 0.81975803 0.54846485
 0.47131457 0.21408416 0.19851596 0.52404702 0.78383481 0.22894833
 0.50260308 0.78768051 0.01762638 0.01367078 0.70042917 0.1567204
 0.47976437 0.70054219 0.90872698 0.789876   0.44441162 0.897226

## Task 20
- create a 10x2 random matrix filled with number from range 0-100
- consider it as points in Cartesian plain
- convert to polar system of coordinates

## Task 21
- create random 13x13 matrix, replace maximal element to zero

## Task 22
- create two 1d arrays with random values
- make a Cauchy matrix from them $C (C_{ij} = \frac{1}{x_i - y_j})$

## Task 23
- create an array of random `float` numbers and convert it to `int`

In [78]:
arr23 = np.random.rand(100) #.astype(np.int)
#arr231 = np.ndarray.astype(int,arr23)
print(arr23)


TypeError: descriptor 'astype' requires a 'numpy.ndarray' object but received a 'type'

## Task 24
- create 1d array of numbers from 0 to 15
- put each of them in random positions inside 4x4 matrix

In [166]:
mat24 = np.arange(0,16).reshape(4,4)

np.random.shuffle(mat24)

print(mat24)

[[12 13 14 15]
 [ 0  1  2  3]
 [ 8  9 10 11]
 [ 4  5  6  7]]


## Task 25
- create random 100x50 matrix
- deduct avarage of each row from correspondatn rows

In [56]:
mat25 = np.random.randint(100,size=(100,50))
print(mat25)

[[29 99 74 ... 55 44 10]
 [67  6 82 ...  8 25 30]
 [77  7 54 ... 51 47 45]
 ...
 [50 40 33 ... 55 50 65]
 [79 13 11 ... 86 36  4]
 [29 23  2 ... 63 23 30]]


## Task 26 
- create random 10x10 matrix
- extract diagonal elements and put them into 1d array

In [218]:
mat26 = np.random.randint(100,size=(10,10))

print(mat26)

vec26 = mat26.diagonal()

print(vec26)

[[ 4 74 61  2 73  4  7 67 73  1]
 [56 24 70 34 88  8 40  5 72 75]
 [84 68 31 15 29  2 88 45 66 26]
 [ 3 65 83 49  8 37 66  8 65 78]
 [79  5 98 40 58 91  6 77 43 55]
 [79  7 38 62 85 84 29 17 90 92]
 [64 84 18 10 29 72  1  0 11 43]
 [76 80  9 88 19 57 99 62  6  1]
 [35 77 50 33 24 88 40  1 75  6]
 [35  4 21 89 70 70 94 32 79  6]]
[ 4 24 31 49 58 84  1 62 75  6]


## Task 27
- given a vector `[1, 2, 3, 4, 5]`
- build a new vertor with three zeros between each element

In [209]:
vecA = np.array([1,2,3,4,5])

arrA = np.array([0,0,0])

#for index.val in enumerate(vecA):
    
    